# ============================================================
# Arma data/synthetic/sinteticos.csv a partir de las 3 salidas del LLM.
# Pega cada salida (un informe por línea) entre las triples comillas.
# Luego corre:  python armar_csv_sinteticos.py
# ============================================================
import csv, re, os
from collections import Counter

b4 = """
    mamografía digital bilateral cráneo-caudal y medio lateral oblicuas piel y complejo areola pezón normales. las mamas se presentan heterogéneamente densas que podría ocultar algunos nódulos pequeños (mamas tipo c). en cse plano medio de mama izquierda se constata asimetría focal en relación a estudio previo, de límites imprecisos y extensión aprox de 14mm. prolongaciones axilares con ganglios normales.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin alteraciones cutaneas ni del pezon. tejido mamario con sectores dispersos de densidad fibroglandular acr tipo b. en cuadrante inferoexterior plano posterior de la mama derecha se aprecia una imagen nodular, de contornos parcialmente definidos, isodensa, de 12 mm de diametro mayor. no se observan calcificaciones sospechosas.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas no se aprecian alteraciones cutáneas ni del mamelón. las mamas son muy densas, lo que disminuye la sensibilidad mamográfica (tipo d). en el cuadrante superoexterno de la mama izquierda, plano posterior, se observa distorsión leve de la arquitectura estromal, sin nódulo dominante claro, mide aprox 18 mm. ganglios axilares bilaterales de aspecto habitual.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones de la piel ni complejos areolo-pezón. parénquima con tejido adiposo casi en su totalidad (mamas tipo a). en csi de mama derecha, plano medio, se identifican microcalcificaciones amorfas agrupadas en número de 8-10, ocupando un área de 8 mm. no se observan masas asociadas. axilas libres.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas plano cutáneo y pezón sin alteraciones. parénquima mamario heterogéneamente denso que puede ocultar lesiones pequeñas (tipo c). en la unión de cuadrantes superiores de la mama derecha, plano anterior, se esboza un nódulo irregular, de contornos microlobulados, discretamente hiperdenso, de 9 mm. calcificaciones vasculares aisladas.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin hallazgos en piel ni pezones. mamas con sectores dispersos de densidad fibroglandular (mamas tipo b). en cuadrante superointerno de mama izquierda, plano medio, se evidencia asimetría focal de contornos parcialmente definidos que mide 16 mm, no presente en estudio de hace dos años. adenopatías axilares inespecíficas.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas no se demuestran alteraciones cutáneas. mamas densas de forma difusa (tipo d). en unión de cuadrantes externos, plano posterior de la mama derecha, se aprecia una imagen de contornos oscurecidos e imprecisos, discretamente hiperdensa, de 11 mm. no se asocian microcalcificaciones de tipo sospechoso. axilas normales.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel y mamelon normales. mamas compuestas por sectores dispersos de densidad fibroglandular (tipo b). en el cuadrante inferointerno de mama izquierda, plano medio, se visualizan microcalcificaciones agrupadas de morfología amorfa en un sector de 7 mm. se sugiere correlación molecular. axila izquierda libre.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas no se observan retracciones de piel ni del pezón. el parénquima es graso casi en su totalidad (acr tipo a). en el cuadrante superoexterno de la mama derecha, plano anterior, se destaca nódulo de forma irregular, isodenso, de contornos microlobulados, diámetro mayor de 13 mm. se visualizan calcificaciones gruesas de aspecto benigno.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos cutáneos sin particularidades. mamas heterogéneamente densas (tipo c). en cse de mama izquierda, plano posterior, se reconoce una distorsión de la arquitectura parenquimatosa, de carácter leve, con sutiles espículas que se extienden en 15 mm. regiones pectoaxilares con ganglios de centro graso.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas revestimiento cutáneo normal, pezones sin retracción. mamas muy densas (tipo d). en la unión de cuadrantes inferiores de mama derecha, plano medio, se observa área de asimetría focal, sutilmente hiperdensa, sin claros márgenes, de 22 mm. requiere magnificación y focalización.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas no se observan alteraciones cutaneas ni del pezon. tejido fibroglandular disperso acr tipo b. en cuadrante superoexterno de mama izquierda, plano medio, se identifica imagen nodular ovalada, hiperdensa, de margenes parcialmente ocultos por el parenquima, de 14 mm de diametro. ganglios axilares bilaterales normales.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel normal, pezón sin alteraciones. mamas predominantemente grasas (tipo a). en cii de mama derecha, plano anterior, se agrupan microcalcificaciones de aspecto amorfo, no concluyentes, ocupando un área de 9 mm, sin nódulo asociado. no hay calcificaciones vasculares.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin alteraciones cutáneas. mamas heterogéneamente densas (tipo c). en unión de cuadrantes superiores de mama izquierda, plano medio, se visualiza un nódulo de densidad media, contornos parcialmente definidos y microlobulados, de 10 mm. imágenes nodulares pectoaxilares con caracteres ganglionares normales.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel y pezón normales. mamas con tejido denso difuso (tipo d). en cse de mama derecha, plano posterior, se observa una pequeña zona de distorsión focal de la arquitectura estromal, de 12 mm, mejor evaluable en proyección oblicua. adenopatías axilares ausentes.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezon sin alteraciones. mamas con sectores dispersos de densidad fibroglandular tipo b. en cuadrante superointerno de mama izquierda, plano anterior, se visualiza una imagen nodular irregular, de contornos mal definidos, isodensa, de 8 mm de diametro. calcificaciones benignas dispersas.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se demuestran alteraciones de la piel ni del mamelón. mamas densas de tipo c. en el cse de la mama derecha, plano medio, se detecta un grupo de microcalcificaciones de morfología amorfa, con unas 12 partículas en un espacio de 10 mm. requiere magnificación complementaria.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel y pezon normales. parénquima de sustitución adiposa casi total (tipo a). en unión de cuadrantes externos de mama izquierda, plano posterior, se evidencia una asimetría focal de densidad moderada, de límites imprecisos, que mide aprox 18 mm. ganglios pectoaxilares normales de centro radiolúcido.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas revestimiento cutáneo de caracteres normales. mamas muy densas (tipo d). en cuadrante inferoexterno de mama derecha, plano medio, se intuye una opacidad nodular de contornos oscurecidos y parcialmente definidos, de 13 mm. se sugiere ecografía mamaria dirigida.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin retracciones cutaneas. tejido mamario con sectores dispersos de densidad fibroglandular acr tipo b. en csi de mama izquierda, plano posterior, se observa un nódulo ovalado, isodenso, de márgenes imprecisos y microlobulados, de 11 mm. calcificaciones vasculares presentes.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas no se observan alteraciones cutáneas ni del pezón. mamas heterogéneamente densas (tipo c). en cuadrante superoexterno de la mama derecha, plano medio, se visualiza una asimetría focal, sutilmente hiperdensa, de contornos mal definidos, que mide 20 mm. regiones axilares libres de adenomegalias.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones en los planos cutáneos. parénquima de tipo a (graso). en cii de mama izquierda, plano anterior, se constata la presencia de un grupo de microcalcificaciones amorfas, de distribución agrupada, que mide 6 mm de extensión máxima. no se asocian nódulos.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel y pezón normales. mamas muy densas (tipo d). en unión de cuadrantes superiores de mama derecha, plano posterior, se sospecha una leve distorsión de la arquitectura estromal, sin masa claramente definida, que compromete unos 14 mm. axila derecha libre de imágenes patológicas.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas no se evidencian alteraciones cutaneas. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el cse de la mama izquierda, plano medio, se identifica una imagen nodular, irregular, discretamente hiperdensa, de contornos parcialmente definidos, que mide 10 mm.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas pezones sin retracción ni alteraciones cutáneas. mamas heterogéneamente densas que disminuyen la sensibilidad (tipo c). en csi de la mama derecha, plano medio, se visualiza una asimetría focal, de límites netamente imprecisos, que alcanza los 15 mm. ganglios con caracteres habituales en ambas axilas.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin alteraciones. parénquima graso casi en su totalidad (tipo a). en cuadrante superoexterno de mama izquierda, plano posterior, se observa un nódulo de densidad intermedia, contornos irregulares y parcialmente definidos, de 12 mm de diámetro mayor.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel normal, mamelón sin alteraciones. mamas de tipo d (muy densas). en el cuadrante inferointerno de la mama derecha, plano anterior, se aprecia grupo de microcalcificaciones de morfología amorfa y heterogénea, en un área de 8 mm. se sugiere evaluación complementaria magnificada.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones de piel ni pezones. mamas compuestas por sectores dispersos de densidad fibroglandular (acr b). en la unión de cuadrantes internos de la mama izquierda, plano medio, se esboza una distorsión leve de la arquitectura, con finas espículas, que mide aprox 11 mm.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se demuestran alteraciones cutáneas. mamas heterogéneamente densas (tipo c). en cse de mama derecha, plano medio, se visualiza una imagen nodular ovalada, isodensa, de márgenes oscurecidos y parcialmente imprecisos, de 16 mm de diámetro mayor. axilas libres.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel y complejo areola pezón normales. mamas de sustitución grasa casi total (tipo a). en cuadrante superointerno de la mama izquierda, plano anterior, se observa una asimetría focal de baja densidad pero de contornos mal definidos, que mide 14 mm. calcificaciones benignas dispersas.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas sin hallazgos en piel ni mamelón. mamas muy densas (tipo d). en unión de cuadrantes inferiores de la mama derecha, plano posterior, se observa un nódulo irregular, de contornos microlobulados, sutilmente hiperdenso, de 9 mm. imágenes nodulares con caracteres ganglionares en axila derecha.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas no se aprecian alteraciones cutaneas ni del pezon. tejido mamario con sectores dispersos de densidad fibroglandular tipo b. en cse de mama izquierda, plano posterior, se destaca un cúmulo de microcalcificaciones amorfas, no concluyentes, ocupando un diámetro de 7 mm.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas planos cutáneos sin particularidades. mamas heterogéneamente densas (mamas tipo c). en cuadrante inferoexterno de la mama derecha, plano medio, se reconoce un área de distorsión leve del tejido conectivo glanduloestromal, de 13 mm de extensión. ganglios axilares normales.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin retracciones cutáneas. parénquima predominantemente graso (tipo a). en csi de mama izquierda, plano medio, se identifica una imagen nodular de forma irregular, de contornos parcialmente definidos, isodensa, de 15 mm de diámetro. se asocian calcificaciones vasculares.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel y pezón normales. mamas marcadamente densas (tipo d). en el cuadrante superoexterno de la mama derecha, plano posterior, impresiona una asimetría focal, hiperdensa, de límites mal definidos, de 17 mm. requiere proyección complementaria o ultrasonido focalizado.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones de la piel. mamas con sectores dispersos de densidad fibroglandular (acr tipo b). en unión de cuadrantes externos de mama izquierda, plano anterior, se observa un nódulo de contornos microlobulados e imprecisos, de densidad media, que mide 11 mm. axilas libres.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas complejo areola pezón sin alteraciones. mamas heterogéneamente densas (tipo c). en cuadrante inferointerno de la mama derecha, plano posterior, se identifica grupo de unas 10 microcalcificaciones de aspecto amorfo en un área de 8 mm. prolongaciones axilares normales.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas no se demuestran alteraciones cutaneas. parénquima de sustitución adiposa (tipo a). en cse de mama izquierda, plano medio, se visualiza una zona de distorsión leve de la arquitectura, con retracción estromal focalizada de 12 mm. imágenes ganglionares habituales bilaterales.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel normal, mamelón sin retracción. mamas de densidad tipo d. en unión de cuadrantes superiores de la mama derecha, plano medio, se visualiza asimetría focal de contornos parcialmente definidos, isodensa, de 19 mm de longitud. se sugiere correlación ecográfica.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin hallazgos en piel. mamas con densidad fibroglandular dispersa (tipo b). en csi de mama izquierda, plano posterior, se reconoce una imagen nodular ovalada, de contornos oscurecidos y en sectores imprecisos, discretamente hiperdensa, de 14 mm. calcificaciones benignas aisladas.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel y complejos areolo-pezón sin particularidades. mamas heterogéneamente densas (tipo c). en cuadrante inferoexterno de mama derecha, plano anterior, se detecta cúmulo de microcalcificaciones amorfas agrupadas, no concluyentes, que ocupan un espacio de 6 mm.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones cutaneas ni del pezon. tejido mamario casi totalmente graso (tipo a). en cse de la mama izquierda, plano medio, se observa una asimetría focalizada de contornos mal definidos, que mide 15 mm. ganglios pectoaxilares con centro graso conservado.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas planos superficiales respetados. parénquima mamario muy denso (tipo d). en unión de cuadrantes inferiores de mama derecha, plano posterior, se esboza un nódulo de forma irregular, de contornos microlobulados, de 10 mm. se asocian calcificaciones puntiformes aisladas.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel sin alteraciones. mamas con sectores dispersos de densidad fibroglandular (acr b). en el cse de la mama derecha, plano posterior, se aprecia distorsión leve de la arquitectura parenquimatosa que mide aprox 16 mm, no claramente visible en incidencias previas.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas mamelón y piel normales. mamas heterogéneamente densas (tipo c). en cuadrante superointerno de la mama izquierda, plano medio, se observa una imagen nodular de densidad media, contornos parcialmente definidos y márgenes oscurecidos, de 13 mm de diámetro. axilas libres.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones de los planos cutáneos. parénquima predominantemente adiposo (tipo a). en cii de mama derecha, plano anterior, se identifica grupo de microcalcificaciones de morfología amorfa, agrupadas, en un sector de 9 mm. no se visualizan masas ni distorsiones.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel y pezones de aspecto normal. mamas difusamente densas (tipo d). en cuadrante superoexterno de la mama izquierda, plano medio, se observa una asimetría focal, sutilmente hiperdensa, de límites imprecisos, que alcanza los 18 mm. requiere incidencias de compresión.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas no se observan alteraciones cutaneas. tejido mamario con sectores dispersos de densidad fibroglandular (tipo b). en unión de cuadrantes internos de mama derecha, plano posterior, se detecta un nódulo irregular, de contornos microlobulados, isodenso, de 11 mm. ganglios axilares normales.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas complejo areola pezón sin retracciones. mamas heterogéneamente densas (tipo c). en csi de la mama izquierda, plano medio, se visualiza una leve distorsión de la arquitectura estromal, sin nódulo evidente, de 14 mm de extensión. calcificaciones vasculares bilaterales.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin hallazgos. mamas de sustitución grasa casi completa (tipo a). en el cse de la mama derecha, plano posterior, se aprecia un área de asimetría focal de contornos mal definidos, que mide 22 mm. se observan ganglios de aspecto habitual en la axila.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel normal, pezón sin alteraciones. mamas muy densas (tipo d). en cuadrante inferoexterno de mama izquierda, plano anterior, se aprecia grupo de microcalcificaciones de aspecto amorfo, no concluyentes, dispuestas en un área de 7 mm. se aconseja magnificación.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones de piel ni pezones. mamas compuestas por sectores dispersos de densidad fibroglandular (tipo b). en unión de cuadrantes superiores de mama derecha, plano medio, se observa imagen nodular de contornos parcialmente definidos y microlobulados, de 12 mm.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas planos cutáneos normales. mamas heterogéneamente densas (tipo c). en el cse de la mama izquierda, plano posterior, se visualiza asimetría focal de densidad moderada, de límites imprecisos, de 15 mm. imágenes nodulares ganglionares normales en prolongación axilar.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin retracciones de la piel. parénquima graso acr tipo a. en csi de mama derecha, plano medio, se identifica una distorsión leve de la arquitectura, con sutiles líneas espiculadas que convergen en un área de 10 mm. calcificaciones benignas dispersas.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel y mamelón de caracteres normales. mamas densas de tipo d. en cuadrante superointerno de mama izquierda, plano posterior, se intuye una opacidad nodular de forma irregular y contornos imprecisos, de 13 mm. se sugiere ecografía mamaria de alta resolución.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas no se evidencian alteraciones cutaneas. mamas con sectores dispersos de densidad fibroglandular (tipo b). en cii de la mama derecha, plano anterior, se constata un cúmulo de microcalcificaciones de morfología amorfa, en número aproximado de 15 partículas en 8 mm.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas complejo areola pezón sin alteraciones. mamas heterogéneamente densas (tipo c). en unión de cuadrantes externos de la mama izquierda, plano medio, se observa un nódulo irregular, isodenso, de contornos parcialmente ocultos y microlobulados, de 14 mm de diámetro mayor.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales normales. parénquima mamario de tipo a (graso). en cse de mama derecha, plano posterior, se visualiza un área de asimetría focal de límites mal definidos, que mide 17 mm. no se asocian calcificaciones de aspecto sospechoso. axilas libres.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel normal, pezón sin retracción. mamas muy densas (tipo d). en el cuadrante inferointerno de la mama izquierda, plano medio, se esboza una distorsión leve de la arquitectura parenquimatosa que abarca aprox 12 mm. requiere evaluación ecográfica dirigida.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones en los contornos cutáneos. mamas con sectores dispersos de densidad fibroglandular (acr b). en csi de mama derecha, plano anterior, se identifica una imagen nodular de forma irregular, de contornos parcialmente definidos, de 9 mm. ganglios axilares de aspecto normal.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas mamelón y piel normales. mamas heterogéneamente densas (tipo c). en cuadrante superoexterno de mama izquierda, plano posterior, se detecta un grupo de microcalcificaciones amorfas, agrupadas de forma no concluyente, en un área de 10 mm. axila izquierda libre.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin retracciones cutaneas. parénquima de sustitución adiposa casi completa (tipo a). en unión de cuadrantes inferiores de mama derecha, plano medio, se visualiza una asimetría focal de contornos imprecisos, que mide 16 mm. calcificaciones vasculares bilaterales.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel y pezón normales. mamas densas tipo d. en cse de la mama izquierda, plano anterior, se observa un nódulo irregular de contornos microlobulados, sutilmente hiperdenso, de 11 mm. imágenes ganglionares normales en ambas regiones pectoaxilares.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin hallazgos patológicos en piel. mamas compuestas por sectores dispersos de densidad fibroglandular (tipo b). en el cii de la mama derecha, plano posterior, se constata una distorsión leve de la arquitectura estromal que mide 13 mm. se sugiere compresión focalizada.
    mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas complejos areolo pezón respetados. mamas heterogéneamente densas (tipo c). en cuadrante superointerno de mama izquierda, plano medio, se aprecia una imagen nodular, ovalada, isodensa, de márgenes parcialmente ocultos por el parénquima adyacente, de 15 mm.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin alteraciones. parénquima predominantemente graso (tipo a). en cse de mama derecha, plano anterior, se detecta un cúmulo de microcalcificaciones amorfas, agrupadas, ocupando un diámetro máximo de 7 mm. no se observan masas asociadas.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas revestimiento cutáneo de caracteres normales. mamas muy densas (tipo d). en la unión de cuadrantes superiores de mama izquierda, plano posterior, se identifica un área de asimetría focal de límites netamente imprecisos, de 21 mm. requiere ecografía complementaria.
    mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel y pezón normales. mamas con densidad fibroglandular dispersa (acr b). en el cse de la mama derecha, plano medio, se visualiza un nódulo de forma irregular, de contornos parcialmente definidos y microlobulados, que mide 12 mm de diámetro mayor.
    mamografía digital bilateral cráneo-caudal y medio lateral oblícuas sin retracciones cutáneas de ningún tipo. mamas heterogéneamente densas (tipo c). en el cuadrante inferoexterno de la mama izquierda, plano posterior, se observa una distorsión leve de la arquitectura parenquimatosa de 14 mm. ganglios de aspecto normal en ambas axilas.
    mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel sin particularidades, mamelon normal. parénquima de sustitución grasa (tipo a). en csi de la mama derecha, plano medio, se aprecia asimetría focal de límites imprecisos y baja densidad, que alcanza los 18 mm. calcificaciones redondeadas benignas aisladas."""


b5 = """
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas las mamas están compuestas por tejido adiposo casi en su totalidad (mamas tipo a). en el cuadrante superoexterno, plano posterior de la mama izquierda, se visualiza una imagen nodular hiperdensa, irregular y de márgenes espiculados, de 16 mm de diámetro mayor, asociada a retracción cutánea focal. se aprecian imágenes ganglionares de densidad aumentada y pérdida de hilio graso en región pectoaxilar izquierda.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se observan alteraciones cutáneas en mama izquierda, evidenciándose franca inversión y retracción del pezón derecho. las mamas están compuestas por sectores dispersos de densidad fibroglandular (mamas tipo b). en la región retroareolar de dicha mama derecha, plano anterior, destaca un nódulo irregular, marcadamente hiperdenso y de contornos espiculados, que mide 22 mm. en la prolongación axilar homolateral se detecta una adenopatía redondeada, densa, de 18 mm.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos pezon-areola sin alteraciones macroscopicas en los planos superficiales. parénquima mamario heterogéneamente denso que podría ocultar algunos nódulos pequeños (acr tipo c). en la unión de cuadrantes externos de la mama izquierda, plano medio, llama la atención una marcada distorsión arquitectural asociada a finas espículas convergentes que se extienden en un área de 30 mm, acompañándose de microcalcificaciones pleomórficas agrupadas.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas marcada retracción cutánea en el cuadrante superoexterno de la mama derecha. las mamas son muy densas, lo que disminuye la sensibilidad mamográfica (tipo d). a nivel del cse de la mama derecha, plano posterior, se identifica una imagen nodular de límites imprecisos, irregular y marcadamente espiculada, con un diámetro aproximado de 19 mm. en la región pectoaxilar derecha se observa una opacidad ganglionar de morfología redondeada y alta densidad.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas no se aprecian alteraciones cutáneas basales. las mamas están compuestas por tejido adiposo casi en su totalidad (mamas tipo a). en el cuadrante superointerno de la mama izquierda, plano posterior, se identifica un grupo de microcalcificaciones lineales finas y ramificadas con franca distribución segmentaria, ocupando un trayecto de 25 mm, sin nódulo dominante visible.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas discreto engrosamiento de la piel periareolar izquierda. las mamas están compuestas por sectores dispersos de densidad fibroglandular (mamas tipo b). en el cuadrante inferointerno de la mama izquierda, plano medio, se constata una masa irregular, hiperdensa, de contornos netamente espiculados, de 14 mm, que genera sutil tiramiento estromal adyacente. región pectoaxilar izquierda con imagen nodular densa que sugiere adenopatía metastásica.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas pezones sin alteraciones exofíticas. las mamas se presentan heterogéneamente densas que podría ocultar algunos nódulos pequeños (american college of radiology tipo c). en cse plano medio de la mama derecha se define una zona de distorsión arquitectural marcada con espículas que retraen el parénquima circundante, asociando microcalcificaciones pleomórficas en su interior, todo ello midiendo unos 18 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel y complejo areola pezon normales. mamas muy densas disminuyendo la sensibilidad de la tecnica (tipo d). en el cuadrante superoexterno de la mama izquierda, plano posterior, se intuye opacidad nodular de morfología irregular y márgenes espiculados, de 15 mm, asociada a microcalcificaciones pleomórficas de distribución ductal. adenopatía axilar izquierda de densidad aumentada.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas retracción de la piel en cuadrante inferoexterno de la mama derecha. parénquima graso casi en su totalidad (mamas tipo a). en dicho cie, plano anterior, se identifica una masa hiperdensa, de forma irregular y contornos fuertemente espiculados de 24 mm de diámetro mayor. no se observan calcificaciones vasculares. región axilar derecha con ganglio alterado en su morfología.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin alteraciones cutaneas. las mamas están compuestas por sectores dispersos de densidad fibroglandular (tipo b). en la unión de cuadrantes superiores de la mama izquierda, plano medio, se visualiza una imagen nodular irregular, hiperdensa, de márgenes imprecisos y groseramente espiculados, que mide 13 mm. se evidencian calcificaciones vasculares en ambas mamas.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas signos de inversión del pezón izquierdo de reciente aparición según refiere la paciente. mamas heterogéneamente densas (acr tipo c). en la región retroareolar izquierda, plano anterior, se localiza un área de distorsión arquitectural marcada con retracción del tejido conectivo adyacente y microcalcificaciones lineales finas de distribución ductal que se extienden por 16 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos cutáneos sin particularidades. mamas compuestas por tejido adiposo casi en su totalidad (mamas tipo a). en csi plano medio de la mama derecha se aprecia un nódulo hiperdenso, marcadamente irregular y espiculado, que mide 11 mm. adyacente al mismo se visualizan microcalcificaciones pleomórficas de distribución segmentaria afectando un área de 12 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas engrosamiento cutáneo difuso en cuadrantes externos de la mama izquierda. parénquima denso tipo d. en el cuadrante superoexterno de la mama izquierda, plano posterior, se evidencia una opacidad de contornos irregulares y francamente espiculados de 28 mm, en íntimo contacto con la fascia pectoral. se asocia a adenopatía axilar izquierda promitente y densa.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas no se visualizan alteraciones en los pezones. parénquima con sectores dispersos de densidad fibroglandular (tipo b). en el cuadrante inferoexterno de la mama derecha, plano medio, se detecta un grupo de microcalcificaciones pleomórficas y lineales finas con franca disposición segmentaria, abarcando una extensión de 18 mm. región pectoaxilar derecha libre.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas evidente retracción de la piel en región periareolar superior derecha. mamas heterogéneamente densas (tipo c). en la unión de cuadrantes superiores de la mama derecha, plano anterior, destaca una masa irregular, de alta densidad y con abundantes espículas que se extienden hacia la dermis, midiendo el cuerpo central unos 17 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas complejos mamelonares normales sin alteraciones cutáneas. mamas grasas tipo a. en el cuadrante superoexterno de la mama derecha, plano medio, se visualiza una imagen nodular irregular, hiperdensa, de márgenes marcadamente espiculados que mide 20 mm de diámetro mayor, asociada a algunas microcalcificaciones pleomórficas intralesionales.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas planos superficiales respetados. mamas muy densas (tipo d). en csi plano posterior de la mama izquierda se sospecha una zona de distorsión arquitectural marcada con finas líneas radiales convergentes, difícil de delimitar por la densidad estromal, midiendo aprox 15 mm. se acompaña de ganglio axilar izquierdo de morfología redondeada.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas no se aprecian alteraciones cutaneas ni del pezon. tejido mamario con sectores dispersos de densidad fibroglandular acr tipo b. en cuadrante inferointerno, plano medio de la mama derecha, se aprecia un nódulo irregular de contornos espiculados, isodenso, de 12 mm de diámetro mayor, que condiciona sutil distorsión local.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas franca retracción y aplanamiento del pezón izquierdo. mamas heterogéneamente densas que disminuyen la sensibilidad (tipo c). en región retroareolar de la mama izquierda, plano anterior, se constata una imagen nodular de contornos irregulares, espiculados, hiperdensa, de 21 mm. prolongación axilar izquierda con adenopatía densa de 15 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin alteraciones cutáneas basales. mamas predominantemente grasas acr tipo a. en la unión de cuadrantes internos de la mama derecha, plano medio, destaca un foco de distorsión arquitectural marcada, con desestructuración del tejido graso circundante en un área de 22 mm, conteniendo microcalcificaciones lineales finas.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas engrosamiento de la piel en la mitad inferior de la mama derecha. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el cii de dicha mama, plano posterior, se identifica una masa irregular, hiperdensa, de contornos imprecisos y espiculados de 31 mm. se visualiza ganglio axilar derecho denso de caracteres sospechosos.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezon sin alteraciones. parénquima de tipo c. en cse plano medio de la mama izquierda se aprecia un cúmulo segmentario de microcalcificaciones pleomórficas, lineales y ramificadas, que ocupan un trayecto ductal de aproximadamente 24 mm de longitud, sin masa nodular evidente.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas alteración cutánea focalizada con hoyuelo en cse de mama derecha. parénquima graso tipo a. en cuadrante superoexterno de la mama derecha, plano medio, se observa una imagen nodular de forma irregular, densidad elevada y márgenes netamente espiculados de 14 mm de diámetro mayor.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel normal pezones sin retracción. mamas muy densas (tipo d). en la unión de cuadrantes superiores de la mama izquierda, plano posterior, se intuye una masa de contornos irregulares y espiculados de 18 mm. en la fosa axilar izquierda se identifica una estructura ganglionar esferoidal, hiperdensa, de 20 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas mamelón izquierdo invertido de forma fija. mamas con sectores dispersos de densidad fibroglandular (tipo b). en la región retroareolar de la mama izquierda se identifica una distorsión arquitectural marcada con retracción del complejo y espículas que se extienden hacia el plano medio, abarcando 25 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin alteraciones de los contornos cutáneos. mamas grasas acr tipo a. en csi de la mama derecha, plano posterior, se visualiza una imagen nodular marcadamente irregular, hiperdensa, de márgenes espiculados, de 13 mm, asociada a un rosario de microcalcificaciones pleomórficas de distribución ductal.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel normal, complejos areola-pezón sin particularidades. mamas heterogéneamente densas (tipo c). en el cuadrante inferointerno de la mama izquierda, plano medio, destaca un área de distorsión arquitectural marcada de 16 mm, con sutiles espículas divergentes, mejor definida en la proyección oblicua mlo.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas retracción cutánea evidente en cse de mama derecha. parénquima denso tipo d. en el cuadrante superoexterno de la mama derecha, plano posterior, se identifica un nódulo irregular, de alta densidad y márgenes francamente espiculados de 23 mm. se acompaña de adenopatía axilar derecha de forma redondeada.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas planos superficiales respetados. mamas compuestas por sectores dispersos de densidad fibroglandular (tipo b). en cii de la mama izquierda, plano anterior, se identifica una imagen nodular irregular, isodensa, de márgenes espiculados, de 10 mm de diámetro, asociada a microcalcificaciones pleomórficas intralesionales.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel y pezon normales. parénquima de sustitución adiposa casi completa (tipo a). en la unión de cuadrantes externos de la mama derecha, plano medio, llama la atención un grupo de microcalcificaciones lineales finas y pleomórficas con clara distribución segmentaria y orientación ductal, abarcando 19 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas signos de engrosamiento cutáneo periareolar derecho. mamas heterogéneamente densas (tipo c). en la región retroareolar de la mama derecha, plano anterior, se identifica una masa irregular, hiperdensa, de contornos marcadamente espiculados que mide 15 mm. la prolongación axilar derecha muestra una opacidad ganglionar redondeada de 16 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas no se aprecian alteraciones cutaneas. mamas muy densas (tipo d). en cse plano posterior de la mama izquierda se delimita con dificultad un foco de distorsión arquitectural marcada con retracción del estroma glandular, que mide aproximadamente 17 mm. región pectoaxilar izquierda libre de nódulos.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas discreto umbilicamiento cutáneo en csi de mama derecha. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el cuadrante superointerno de la mama derecha, plano medio, se aprecia una imagen nodular irregular, hiperdensa y de márgenes espiculados, de 12 mm de diámetro mayor.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin alteraciones. parénquima mamario predominantemente graso (tipo a). en cuadrante inferoexterno de la mama izquierda, plano posterior, destaca una masa irregular, densa, de contornos espiculados de 26 mm de diámetro, que ejerce tracción sobre la fascia posterior.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel normal, complejos areola-pezón simétricos. mamas heterogéneamente densas (tipo c). en cse plano medio de la mama derecha se identifica una distorsión arquitectural marcada, asociada a microcalcificaciones pleomórficas y lineales finas de distribución segmentaria, comprometiendo un área de 21 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas franca inversión del pezón derecho. mamas de densidad tipo d. en región retroareolar de la mama derecha, plano anterior, se visualiza un nódulo irregular, hiperdenso, de márgenes espiculados de 18 mm. en la región pectoaxilar derecha destaca una adenopatía densa, esferoidal y sin hilio graso de 19 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas no se demuestran alteraciones de la piel. mamas compuestas por sectores dispersos de densidad fibroglandular (acr b). en la unión de cuadrantes inferiores de la mama izquierda, plano medio, se observa una imagen nodular irregular, isodensa, de márgenes espiculados, que mide 14 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel e hilos mamelonares normales. mamas predominantemente grasas (tipo a). en el cuadrante superoexterno de la mama derecha, plano posterior, se identifica un grupo de microcalcificaciones pleomórficas de distribución ductal, dispuestas en un trayecto de 15 mm, sin masa asociada visible.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas retracción cutánea focal en la unión de cuadrantes superiores de la mama izquierda. parénquima de tipo c. en dicha unión de cuadrantes, plano anterior, se observa una masa hiperdensa de forma irregular y contornos fuertemente espiculados de 16 mm de diámetro mayor.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin hallazgos. mamas de densidad tipo d. en csi de la mama derecha, plano medio, se detecta un área de distorsión arquitectural marcada con líneas espiculadas convergentes que abarca unos 14 mm. se acompaña de una opacidad ganglionar axilar homolateral redondeada.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas engrosamiento cutáneo y retracción del pezón izquierdo. mamas con sectores dispersos de densidad fibroglandular (tipo b). en región retroareolar de la mama izquierda se observa una masa irregular, densa y espiculada de 25 mm. en axila izquierda se visualiza adenopatía de morfología alterada y alta densidad.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas no se observan alteraciones de la piel. mamas grasas tipo a. en cuadrante inferoexterno de la mama derecha, plano medio, destaca una imagen nodular irregular, de contornos espiculados, hiperdensa, de 11 mm, asociada a finas microcalcificaciones pleomórficas intralesionales.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas complejo areola pezón sin retracciones. mamas heterogéneamente densas (tipo c). en cse plano posterior de la mama izquierda se constata una marcada distorsión arquitectural con espículas que retraen el parénquima vecino, ocupando un área de aproximadamente 20 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel normal. mamas muy densas (tipo d). en la unión de cuadrantes externos de la mama derecha, plano medio, se intuye una opacidad nodular irregular con márgenes espiculados de 13 mm. en fosa axilar derecha se observa un ganglio linfático esferoidal, denso, sospechoso.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas retracción de la piel en csi de la mama izquierda. mamas con sectores dispersos de densidad fibroglandular (tipo b). en dicho cuadrante, plano anterior, se visualiza una masa irregular, hiperdensa y de contornos espiculados, con un diámetro de 17 mm. calcificaciones benignas aisladas.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales normales. parénquima graso acr tipo a. en el cuadrante superoexterno de la mama derecha, plano posterior, llama la atención un cúmulo segmentario de microcalcificaciones lineales finas y pleomórficas que siguen un trayecto ductal de 22 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas pezón derecho desviado con retracción cutánea adyacente. mamas heterogéneamente densas (tipo c). en región retroareolar de la mama derecha, plano anterior, se identifica un nódulo irregular, hiperdenso, de márgenes espiculados de 15 mm. adenopatía axilar derecha redondeada y densa de 14 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin alteraciones cutaneas. mamas marcadamente densas (tipo d). en cse plano posterior de la mama izquierda se aprecia una zona de distorsión arquitectural marcada con desestructuración del tejido conectivo que mide unos 16 mm. requiere compresión focalizada y magnificación.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas complejos areolo pezón normales. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el cuadrante inferointerno de la mama derecha, plano medio, se localiza un nódulo irregular, de contornos espiculados, isodenso, de 12 mm de diámetro mayor.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas piel normal. parénquima predominantemente adiposo (tipo a). en la unión de cuadrantes inferiores de la mama izquierda, plano medio, se visualiza una distorsión arquitectural marcada asociada a microcalcificaciones pleomórficas de distribución segmentaria, todo en un área de 18 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas hoyuelo cutáneo visible en cse de la mama derecha. mamas heterogéneamente densas (tipo c). en dicho cuadrante, plano posterior, se identifica una masa irregular, hiperdensa, de contornos marcadamente espiculados que mide 20 mm. adenopatía axilar homolateral densa de 17 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas pezones sin retracción ni secreciones. mamas densas tipo d. en csi de la mama izquierda, plano medio, se observa un área de distorsión arquitectural marcada con finas espículas, de aproximadamente 13 mm de extensión. se aconseja correlación con ultrasonido.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas retracción focal de la piel en cuadrante inferoexterno de la mama derecha. parénquima graso tipo a. en dicho cie, plano anterior, destaca un nódulo irregular, hiperdenso y de contornos espiculados de 14 mm. no se aprecian calcificaciones de aspecto benigno.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin alteraciones. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el cuadrante superoexterno de la mama izquierda, plano medio, se identifica un grupo de microcalcificaciones pleomórficas y lineales finas de distribución ductal, abarcando 16 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas inversión reciente del pezón izquierdo con engrosamiento cutáneo focal. mamas heterogéneamente densas (tipo c). en región retroareolar izquierda, plano anterior, se define una masa irregular, densa y de márgenes netamente espiculados de 22 mm. adenopatía axilar izquierda sospechosa.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin alteraciones de los pezones. parénquima graso acr tipo a. en csi plano posterior de la mama derecha se aprecia un nódulo irregular, isodenso, de contornos espiculados, que mide 11 mm, asociado a sutiles microcalcificaciones pleomórficas intralesionales.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas piel normal. mamas muy densas disminuyendo la sensibilidad de la técnica (tipo d). en la unión de cuadrantes superiores de la mama izquierda, plano medio, se sospecha distorsión arquitectural marcada con retracción estromal, de unos 15 mm. ganglio axilar izquierdo redondeado y denso.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezon normales sin alteraciones cutáneas. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el cse de la mama derecha, plano posterior, se visualiza una masa irregular, hiperdensa, de márgenes francamente espiculados de 19 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas marcada retracción cutánea en cuadrante inferointerno de la mama izquierda. mamas heterogéneamente densas (tipo c). en dicho cii, plano anterior, destaca un nódulo irregular, de alta densidad y márgenes espiculados de 16 mm de diámetro mayor.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales respetados. parénquima de sustitución adiposa casi completa (tipo a). en la unión de cuadrantes externos de la mama derecha, plano medio, se constata una distorsión arquitectural marcada con desestructuración del tejido conectivo en un área de 21 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas engrosamiento cutáneo difuso en la mama izquierda con retracción del mamelón. mamas densas tipo d. en cse plano posterior de la mama izquierda se identifica una masa irregular y espiculada de 30 mm. en la prolongación axilar se observa una adenopatía de morfología alterada.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas no se demuestran alteraciones cutaneas. mamas con sectores dispersos de densidad fibroglandular (acr b). en csi de la mama derecha, plano medio, se detecta un grupo de microcalcificaciones pleomórficas de distribución ductal, dispuestas en una extensión de 14 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas retracción de la piel en la región periareolar inferior derecha. mamas heterogéneamente densas (tipo c). en la unión de cuadrantes inferiores de la mama derecha, plano anterior, destaca una masa irregular, hiperdensa y de contornos espiculados de 15 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin hallazgos. parénquima mayoritariamente graso (tipo a). en cuadrante inferoexterno de la mama izquierda, plano posterior, se observa un nódulo irregular, de contornos espiculados, de 12 mm, asociado a microcalcificaciones pleomórficas.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas pezón izquierdo umbilicado con engrosamiento cutáneo periareolar. mamas muy densas (tipo d). en región retroareolar izquierda se intuye una masa irregular de contornos espiculados de 18 mm. se acompaña de estructura ganglionar axilar esferoidal, densa, de 16 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas sin retracciones cutáneas. mamas con sectores dispersos de densidad fibroglandular (tipo b). en cse plano medio de la mama derecha se localiza un foco de distorsión arquitectural marcada de 14 mm con finas líneas radiales que convergen centrípetamente.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas alteración cutánea focalizada con retracción en csi de la mama izquierda. mamas heterogéneamente densas (tipo c). en dicho cuadrante, plano anterior, se visualiza un nódulo irregular, hiperdenso, de contornos espiculados que mide 13 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezon simétricos sin alteraciones. parénquima graso acr tipo a. en la unión de cuadrantes superiores de la mama derecha, plano posterior, se identifica un cúmulo segmentario de microcalcificaciones lineales finas y ramificadas que abarca 20 mm.
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas retracción del pezón derecho con engrosamiento de la piel adyacente. mamas densas tipo d. en región retroareolar de la mama derecha, plano anterior, destaca una masa irregular, hiperdensa y marcadamente espiculada de 17 mm. adenopatía axilar derecha redondeada de 15 mm.
mamografia digitalizada bilateral craneo-caudal y medio lateral oblicuas planos superficiales respetados. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el cuadrante inferointerno de la mama izquierda, plano medio, se identifica un nódulo irregular, de contornos espiculados, isodenso, de 11 mm de diámetro mayor, que deforma discretamente la arquitectura estromal circundante.
"""

b6 = """
mamografía digital bilateral cráneo-caudal y medio lateral oblícuas no se observan alteraciones cutáneas ni del pezón. las mamas están compuestas por sectores dispersos de densidad fibroglandular (mamas tipo b). en el cuadrante superoexterno, plano medio de la mama izquierda, se visualiza una imagen nodular irregular, hiperdensa y de márgenes espiculados, de 16 mm de diámetro mayor, que presenta marcador de clip metálico post-biopsia en su centro, en contexto de proceso neoplásico conocido. calcificaciones vasculares aisladas.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas plano cutáneo sin alteraciones. las mamas se presentan heterogéneamente densas que podría ocultar algunos nódulos pequeños (american college of radiology tipo c). en cse de mama derecha, plano posterior, se identifica distorsión de la arquitectura con clip metálico central en relación a lesión maligna ya confirmada, midiendo el área densa unos 22 mm, estable respecto a estudio previo. ganglios axilares de aspecto habitual.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin alteraciones de la piel ni complejos areolo-pezón. parénquima con tejido adiposo casi en su totalidad (mamas tipo a). en cuadrante superoexterno, plano medio de la mama derecha, persiste imagen nodular irregular, hiperdensa y espiculada de 25 mm, asociada a clip post-biopsia intralesional por carcinoma ya diagnosticado. imágenes nodulares con caracteres ganglionares en región pectoaxilar derecha.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas se aprecia retracción cutánea focal en cse izquierdo. las mamas son muy densas, lo que disminuye la sensibilidad mamográfica (tipo d). en el cuadrante superoexterno, plano posterior de mama izquierda, se observa masa irregular y espiculada de 18 mm que engloba clip marcador post-procedimiento, en seguimiento por malignidad conocida sin cambios significativos. axila izquierda libre.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas pezones sin alteraciones exofíticas. mamas con sectores dispersos de densidad fibroglandular (tipo b). en la unión de cuadrantes superiores de la mama derecha, plano medio, se delimita imagen nodular irregular, de márgenes espiculados, de 14 mm, que contiene clip metálico de biopsia, hallazgo ya conocido en control por carcinoma ductal. calcificaciones puntiformes dispersas.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se aprecian alteraciones en los planos superficiales. mamas heterogéneamente densas (acr tipo c). en csi de la mama izquierda, plano anterior, se visualiza distorsión de la arquitectura asociada a densificación estromal de 12 mm y clip de marcación por lesión maligna confirmada, sin modificaciones mayores en comparación al estudio basal. axilas libres.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos mamelonares normales. parénquima de sustitución adiposa casi completa (tipo a). en el cuadrante inferointerno de la mama derecha, plano medio, se evidencia nódulo irregular, hiperdenso y espiculado de 20 mm, con clip metálico en su espesor en relación a neoplasia conocida. imágenes nodulares con caracteres ganglionares en ambas regiones pectoaxilares.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas discreto engrosamiento cutáneo en región retroareolar izquierda. mamas muy densas (tipo d). en zona retroareolar de mama izquierda, plano anterior, persiste masa irregular, hiperdensa y espiculada de 28 mm, que asocia clip marcador central por lesión maligna ya delimitada en mamografía anterior. adenopatía axilar izquierda sospechosa de 15 mm.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas sin retracciones en la piel. mamas compuestas por sectores dispersos de densidad fibroglandular (mamas tipo b). en cuadrante inferoexterno de la mama derecha, plano posterior, se identifica imagen nodular irregular, de contornos espiculados y 11 mm de diámetro mayor, conteniendo clip post-biopsia por carcinoma confirmado. regiones pectoaxilares libres.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel y pezones normales. las mamas se presentan heterogéneamente densas que podría ocultar algunos nódulos pequeños (american college of radiology tipo c). en la unión de cuadrantes externos de la mama izquierda, plano medio, destaca masa irregular de 31 mm, espiculada, con clip de marcación intralesional, hallazgo conocido en control oncológico.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin particularidades. parénquima graso acr tipo a. en cse de mama derecha, plano posterior, se visualiza imagen nodular irregular, hiperdensa, de márgenes espiculados, de 15 mm, que incluye clip metálico post-biopsia por proceso neoplásico ya diagnosticado. calcificaciones vasculares bilaterales.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas retracción de la piel en cse derecho. mamas muy densas (tipo d). en el cuadrante superoexterno de la mama derecha, plano posterior, se constata distorsión arquitectural con densidad central e imprecisa de 24 mm y clip marcador post-biopsia por carcinoma conocido, estable respecto a previo. ganglios axilares de aspecto habitual.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezón normales. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el csi de la mama izquierda, plano anterior, se observa una imagen nodular irregular, hiperdensa y espiculada de 13 mm con clip post-biopsia central, ya delimitada en mamografía anterior en contexto de lesión maligna.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se demuestran alteraciones cutáneas. mamas de densidad tipo c. en unión de cuadrantes inferiores de la mama derecha, plano medio, se identifica nódulo irregular, de contornos espiculados, de 17 mm de diámetro, con clip metálico en su interior por neoplasia confirmada histológicamente. axila derecha con ganglios habituales.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos cutáneos sin hallazgos. parénquima de sustitución grasa casi total (tipo a). en cse de la mama izquierda, plano medio, persiste imagen nodular irregular, hiperdensa, de márgenes netamente espiculados de 19 mm, que engloba clip marcador post-biopsia por malignidad conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas franca inversión del pezón izquierdo de aspecto crónico. mamas densas de tipo d. en región retroareolar izquierda, plano anterior, se sospecha masa irregular con espículas periféricas que mide aprox 23 mm, conteniendo artefacto de clip metálico por carcinoma ya confirmado. adenopatía axilar izquierda de densidad aumentada.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel sin retracciones. mamas compuestas por sectores dispersos de densidad fibroglandular (acr b). en el cuadrante inferoexterno de la mama derecha, plano posterior, se visualiza nódulo irregular, hiperdenso y espiculado de 14 mm con clip post-biopsia en su interior, en control por proceso neoplásico conocido.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se observan alteraciones de la piel ni del mamelón. mamas heterogéneamente densas (tipo c). en cse plano medio de la mama izquierda se observa una zona de distorsión de la arquitectura y densidad asimétrica de 18 mm que asocia clip metálico post-biopsia de lesión maligna ya diagnosticada.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezón sin retracciones. parénquima mayoritariamente graso (tipo a). en la unión de cuadrantes internos de la mama derecha, plano medio, destaca masa irregular, hiperdensa, de contornos marcadamente espiculados de 26 mm, con clip de marcación central por lesión neoplásica confirmada.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas signos de engrosamiento cutáneo focal en cuadrantes externos izquierdos. mamas muy densas (tipo d). en cse de la mama izquierda, plano posterior, se aprecia área de distorsión arquitectural marcada de 21 mm con clip metálico post-biopsia intralesional por carcinoma conocido, sin cambios con respecto al control anterior.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales respetados. mamas con sectores dispersos de densidad fibroglandular (tipo b). en el csi de la mama derecha, plano anterior, se observa una imagen nodular de forma irregular, densidad elevada y márgenes espiculados de 15 mm, conteniendo clip post-biopsia en contexto de malignidad confirmada.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel normal, pezones sin alteraciones. mamas heterogéneamente densas (tipo c). en cse plano medio de la mama izquierda se delimita imagen nodular irregular, de contornos espiculados, que mide 18 mm y muestra clip marcador post-biopsia de proceso maligno ya conocido. ganglios axilares normales.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezón simétricos. parénquima predominantemente adiposo (tipo a). en cuadrante inferoexterno de la mama derecha, plano medio, persiste nódulo irregular, hiperdenso, de contornos espiculados de 12 mm con clip marcador post-biopsia por carcinoma ductal confirmado.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas leve umbilicamiento cutáneo en cse derecho. mamas de densidad tipo d. en el cuadrante superoexterno de la mama derecha, plano posterior, se detecta distorsión de la arquitectura con densidad asimétrica que mide 20 mm, asociando clip post-biopsia por lesión neoplásica conocida. axila derecha libre.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel sin particularidades. mamas compuestas por sectores dispersos de densidad fibroglandular (acr b). en la unión de cuadrantes superiores de la mama izquierda, plano posterior, se visualiza imagen nodular irregular, hiperdensa, de contornos espiculados, de 17 mm, que contiene clip metálico post-biopsia por malignidad conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas pezones sin retracción ni secreciones. mamas heterogéneamente densas (tipo c). en csi de la mama derecha, plano medio, se identifica nódulo irregular, isodenso, de contornos espiculados de 13 mm con clip marcador de biopsia en su espesor, en control por carcinoma ya diagnosticado.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin hallazgos. parénquima de sustitución grasa casi completa (tipo a). en el cuadrante inferointerno de la mama izquierda, plano anterior, se observa masa irregular, hiperdensa, de márgenes fuertemente espiculados de 22 mm, conteniendo clip metálico por proceso maligno conocido.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas engrosamiento cutáneo difuso en cuadrantes externos de mama derecha. mamas muy densas (tipo d). en cse de la mama derecha, plano posterior, se intuye área de distorsión arquitectural de 25 mm con clip metálico post-biopsia por lesión neoplásica conocida. adenopatía axilar derecha redondeada de 16 mm.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezón normales. mamas con sectores dispersos de densidad fibroglandular (tipo b). en la unión de cuadrantes externos de la mama izquierda, plano medio, persiste imagen nodular irregular, de contornos espiculados, de 16 mm de diámetro, con clip marcador intralesional por carcinoma ya confirmado.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel normal. mamas heterogéneamente densas que disminuyen la sensibilidad (tipo c). en cse plano posterior de la mama derecha se identifica distorsión estromal con nódulo irregular y espiculado de 19 mm que engloba clip metálico de marcación por malignidad conocida. axilas libres.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales normales. parénquima predominantemente graso (tipo a). en csi de la mama izquierda, plano anterior, se visualiza imagen nodular irregular, hiperdensa, de márgenes espiculados, de 14 mm, conteniendo clip marcador post-biopsia por lesión maligna ya confirmada.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas franca retracción cutánea focal en cse izquierdo. mamas de densidad tipo d. en el cuadrante superoexterno de la mama izquierda, plano medio, destaca masa irregular, hiperdensa y marcadamente espiculada de 27 mm, que asocia clip metálico central en seguimiento de carcinoma conocido.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas pezones sin alteraciones. mamas compuestas por sectores dispersos de densidad fibroglandular (acr b). en el cuadrante inferoexterno de la mama derecha, plano medio, se observa nódulo irregular, isodenso, de contornos espiculados de 12 mm, con clip marcador post-biopsia de proceso neoplásico ya diagnosticado.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se demuestran alteraciones cutáneas. mamas heterogéneamente densas (tipo c). en la unión de cuadrantes superiores de la mama izquierda, plano posterior, persiste distorsión arquitectural marcada de 18 mm con clip metálico en su centro, en control por neoplasia conocida sin cambios mayores.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos cutáneos sin particularidades. parénquima graso casi en su totalidad (tipo a). en cse de la mama derecha, plano medio, destaca una masa irregular, hiperdensa, de márgenes espiculados de 23 mm, que engloba clip marcador post-biopsia por lesión maligna ya confirmada. calcificaciones vasculares.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas retracción y aplanamiento del pezón derecho. mamas muy densas (tipo d). en región retroareolar de la mama derecha, plano anterior, se identifica imagen nodular irregular, hiperdensa y espiculada de 21 mm con clip metálico post-biopsia central por carcinoma confirmado. ganglio axilar derecho denso de 14 mm.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complexes pezon-areola normales. mamas con sectores dispersos de densidad fibroglandular (tipo b). en csi de la mama izquierda, plano posterior, se visualiza nódulo irregular, de contornos espiculados y 15 mm de diámetro, conteniendo clip de marcación por malignidad conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas piel normal. mamas heterogéneamente densas (tipo c). en el cuadrante inferointerno de la mama derecha, plano medio, se observa área de distorsión de la arquitectura de 16 mm con clip metálico post-biopsia intralesional, correspondiente a foco neoplásico ya diagnosticado. axila libre.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales respetados. parénquima predominantemente graso acr tipo a. en unión de cuadrantes externos de la mama izquierda, plano posterior, persiste imagen nodular irregular, hiperdensa, de márgenes espiculados de 18 mm, con clip marcador post-biopsia por carcinoma ductal conocido.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas hoyuelo cutáneo visible en cse izquierdo. mamas de densidad tipo d. en el cuadrante superoexterno de la mama izquierda, plano posterior, se constata masa irregular, densa y espiculada de 24 mm que incluye clip metálico post-biopsia por proceso maligno confirmado. adenopatía axilar homolateral de 15 mm.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas pezones sin retracción. mamas compuestas por sectores dispersos de densidad fibroglandular (tipo b). en cse plano medio de la mama derecha se identifica una imagen nodular irregular, de contornos espiculados, de 13 mm, con clip marcador intralesional por carcinoma ya delimitado en estudio previo.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se observan alteraciones de la piel. mamas heterogéneamente densas (tipo c). en la unión de cuadrantes inferiores de la mama izquierda, plano anterior, destaca nódulo irregular, isodenso y espiculado de 14 mm, conteniendo clip post-biopsia en contexto de proceso maligno conocido.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezón normales. parénquima graso tipo a. en cuadrante inferoexterno de la mama derecha, plano medio, se visualiza masa irregular, hiperdensa, de contornos espiculados de 20 mm, que asocia clip de marcación central por lesión maligna confirmada histológicamente.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas signos de engrosamiento cutáneo focal en cse derecho. mamas muy densas (tipo d). en cse de la mama derecha, plano posterior, se intuye distorsión de la arquitectura con densidad central de 22 mm y clip marcador post-biopsia por carcinoma conocido, sin variaciones significativas.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales normales. mamas con sectores dispersos de densidad fibroglandular (acr b). en el csi de la mama izquierda, plano posterior, persiste nódulo irregular, hiperdenso, de contornos espiculados de 16 mm, conteniendo clip post-biopsia por neoplasia conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas pezones sin retracción ni desviaciones. mamas heterogéneamente densas (tipo c). en cse plano medio de la mama derecha se identifica área de distorsión arquitectural de 17 mm con clip metálico central, hallazgo conocido en seguimiento por carcinoma ductal confirmado.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel sin particularidades. parénquima mayoritariamente adiposo (tipo a). en la unión de cuadrantes superiores de la mama izquierda, plano anterior, se observa una imagen nodular irregular, hiperdensa y espiculada de 15 mm con clip marcador post-biopsia de lesión maligna conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas evidente retracción de la piel en cuadrantes externos derechos. mamas densas tipo d. en cse de la mama derecha, plano medio, destaca masa irregular, de alta densidad y márgenes francamente espiculados de 26 mm, con clip marcador intralesional por carcinoma conocido. adenopatía axilar derecha de 17 mm.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezón simétricos. mamas compuestas por sectores dispersos de densidad fibroglandular (tipo b). en el cuadrante inferoexterno de la mama izquierda, plano posterior, se localiza nódulo irregular, isodenso, de contornos espiculados de 11 mm, conteniendo clip marcador de biopsia por malignidad conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas planos superficiales sin hallazgos. mamas heterogéneamente densas que deprimen la sensibilidad (tipo c). en csi de la mama derecha, plano medio, persiste distorsión arquitectural marcada de 14 mm con clip metálico en su espesor, en control por lesión neoplásica confirmada.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel normal pezones sin retracción. parénquima predominantemente graso (tipo a). en cse de la mama izquierda, plano posterior, se visualiza masa irregular, hiperdensa, de contornos espiculados de 19 mm, con clip de marcación central por carcinoma ya diagnosticado. calcificaciones benignas dispersas.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas inversión del pezón izquierdo con engrosamiento cutáneo periareolar. mamas muy densas (tipo d). en región retroareolar de la mama izquierda, plano anterior, se observa una masa irregular y espiculada de 23 mm que engloba clip metálico post-biopsia por proceso neoplásico conocido. adenopatía axilar izquierda densa de 15 mm.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales respetados. mamas con sectores dispersos de densidad fibroglandular (acr b). en la unión de cuadrantes internos de la mama derecha, plano medio, se observa una imagen nodular irregular, de contornos espiculados, de 13 mm, conteniendo clip marcador post-biopsia por malignidad confirmada.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas complejos mamelonares normales. mamas heterogéneamente densas (tipo c). en cuadrante inferoexterno de la mama izquierda, plano anterior, destaca nódulo irregular, hiperdenso y espiculado de 14 mm, con clip marcador intralesional en relación a foco neoplásico ya conocido.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel sin retracciones. parénquima de sustitución adiposa casi completa (tipo a). en cse de la mama derecha, plano medio, se identifica masa irregular, hiperdensa, de contornos marcadamente espiculados de 21 mm, que engloba clip marcador post-biopsia por lesión maligna confirmada.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas signos de engrosamiento cutáneo focal en cse izquierdo. mamas densas tipo d. en el cuadrante superoexterno de la mama izquierda, plano posterior, se intuye distorsión de la arquitectura de 20 mm con clip metálico central, hallazgo conocido en seguimiento por carcinoma ductal confirmado. axila libre.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas pezones normales. mamas compuestas por sectores dispersos de densidad fibroglandular (tipo b). en el csi de la mama derecha, plano posterior, persiste imagen nodular irregular, hiperdensa, de contornos espiculados de 15 mm, conteniendo clip marcador post-biopsia por neoplasia ya conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se demuestran alteraciones de la piel. mamas heterogéneamente densas (tipo c). en la unión de cuadrantes superiores de la mama izquierda, plano medio, se visualiza área de distorsión arquitectural de 16 mm con clip metálico intralesional, correspondiente a proceso maligno ya confirmado.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales sin particularidades. parénquima mayoritariamente graso (tipo a). en cse de la mama derecha, plano anterior, destaca una masa irregular, hiperdensa y espiculada de 17 mm con clip marcador post-biopsia por lesión maligna ya confirmada histológicamente.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas franca retracción y aplanamiento del pezón derecho. mamas muy densas (tipo d). en región retroareolar de la mama derecha se observa una masa irregular y espiculada de 25 mm que engloba clip metálico post-biopsia de proceso maligno conocido. adenopatía axilar derecha de forma redondeada y alta densidad.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezón simétricos. mamas con sectores dispersos de densidad fibroglandular (acr b). en cuadrante inferoexterno de la mama izquierda, plano posterior, se localiza nódulo irregular, isodenso, de contornos espiculados de 12 mm, conteniendo clip marcador de biopsia por neoplasia conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas planos superficiales sin hallazgos. mamas heterogéneamente densas (tipo c). en csi de la mama derecha, plano medio, persiste distorsión arquitectural marcada de 15 mm con clip metálico en su espesor, en control por lesión neoplásica conocida sin cambios significativos.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas piel normal pezones sin retracción. parénquima predominantemente adiposo (tipo a). en cse de la mama izquierda, plano posterior, se visualiza masa irregular, hiperdensa, de contornos espiculados de 18 mm, con clip de marcación central por carcinoma ya diagnosticado.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas umbilicamiento cutáneo focal en cse derecho. mamas de densidad tipo d. en el cuadrante superoexterno de la mama derecha, plano medio, destaca masa irregular, densa y espiculada de 22 mm que incluye clip metálico post-biopsia por proceso maligno confirmado. adenopatía axilar homolateral densa de 14 mm.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas pezones sin retracción. mamas compuestas por sectores dispersos de densidad fibroglandular (tipo b). en cse plano medio de la mama izquierda se identifica una imagen nodular irregular, de contornos espiculados, de 14 mm, con clip marcador intralesional por carcinoma ya conocido.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas no se observan alteraciones de la piel. mamas heterogéneamente densas (tipo c). en la unión de cuadrantes inferiores de la mama derecha, plano anterior, se identifica nódulo irregular, isodenso y espiculado de 13 mm, conteniendo clip post-biopsia en contexto de proceso maligno ya diagnosticado.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas complejos areolo pezón normales. parénquima graso tipo a. en cuadrante inferoexterno de la mama izquierda, plano medio, se visualiza masa irregular, hiperdensa, de contornos espiculados de 19 mm, que asocia clip de marcación central por lesión neoplásica confirmada.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas signos de engrosamiento cutáneo focal en cse derecho. mamas muy densas (tipo d). en cse de la mama derecha, plano posterior, se intuye distorsión de la arquitectura con densidad central de 21 mm y clip marcador post-biopsia por carcinoma conocido, estable respecto a control previo.
mamografia digital bilateral craneo-caudal y medio lateral oblicuas planos superficiales normales. mamas con sectores dispersos de densidad fibroglandular (acr b). en el csi de la mama izquierda, plano posterior, persiste nódulo irregular, hiperdenso, de contornos espiculados de 14 mm, conteniendo clip post-biopsia por neoplasia conocida.
mamografía digitalizada bilateral cráneo-caudal y medio lateral oblícuas pezones sin retracción ni desviaciones. mamas heterogéneamente densas (tipo c). en cse plano medio de la mama derecha se identifica área de distorsión arquitectural de 16 mm con clip metálico central, hallazgo conocido en seguimiento por carcinoma ductal confirmado."""

def limpiar(bloque):
    lineas = []
    for l in bloque.strip().split("\n"):
        l = l.strip()
        if not l: continue
        l = re.sub(r'^\s*\d+[\.\)\-]\s*', '', l)   # quita numeración si la hay
        l = l.strip('"').strip()
        if len(l) > 20:
            lineas.append(l)
    return lineas

filas = ([(t,4) for t in limpiar(b4)] +
         [(t,5) for t in limpiar(b5)] +
         [(t,6) for t in limpiar(b6)])

os.makedirs("../data/synthetic", exist_ok=True)
ruta = "../data/synthetic/sinteticos.csv"
with open(ruta, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f); w.writerow(["texto", "BI-RADS"]); w.writerows(filas)

textos = [t for t,_ in filas]
print(f"CSV creado en {ruta}")
print(f"Total: {len(filas)} | Únicos: {len(set(textos))}")
print("Mencionan categoría (deben ser 0):",
      sum(bool(re.search(r'bi.?rads|categoria', t, re.I)) for t in textos))
print("Por clase:", dict(Counter(b for _,b in filas)))
